### ISSUE TITLE
Create welcome view

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-frontend#18]
We should have some greeter on the index page.

**Comment by tillmo** [comment]
Here a first suggestion:
Repositories and proof tools for *O*ntologies, *M*odels and *S*pecifications (OMS)
- Open - based on open source software
- Flexible - different logics are available: OWL, RDF, UML, first-order logic, TPTP, higher-order logic, THF, ...
- Distributed - OMS alignments, mappings, networks, combinations, using [DOL](http://dol-omg.org)
