### ISSUE TITLE
Code conventions

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-frontend#260]
I think the current file and code structure is a bit confusing and inconsistent. So let's discuss some conventions:

1. Components vs. Containers vs. Scenes
1. Testability of Code
1. Test file locations
1. Helpers (functions)
1. Helpers (components)
1. Exports (named vs default)
1. Class components vs. functional components
1. ...?

## Components vs. Containers vs. Scenes

We currently have the directories `components`, `containers` and `scenes`, all of which contain collections of React components.

The distinction between components and containers is one that many react code bases make to distinguish between *pure* (`components`) and *impure* (`container`) components. Containers would be slim wrappers around pure components, so that the pure components can be tested without mocking a ton of stuff.

Think about this like you would in Haskell using IO: You can use pure functions inside the IO monad but you can't use IO functions in pure functions. Because of this you try to keep IO at a very high level and pass a lot of arguments through multiple layers of functions.

The `scenes` directory comes from another convention to group components by the *scenes* (basically routes; in traditional websites these would be separate pages) they are used in. This prevents `component` directories from becoming large and hard to manage.

### Proposed convention

Discard the `container` terminology and export a pure component version and impure from the same file:

```javascript
export const PureSignUpForm = ...

export const SignUpForm = wrap(PureSignUpForm);
```

Keep the `scenes` structure. Each scene can have its own `components` directory. Components in there should only be used by this scene or sub-scenes of this scene. If a component is needed by another separate scene, move the component to the common ancestor. If there is none, move it to the global `components` directory (like lifting state up in React).

```
- components # globally used components
  |- AComponent.js
  `- SomeComponent.js
- scenes
  |- Home
  |  |- components # components used only in the `Home` scene
  |  |  |- AComponent.js
  |  |  `- Header.js
  |  `- index.js # exports relevant data for this scene (e.g. a header and a body component)
  `- OrganizationalUnit
      |- components # components only used in the `OrganizationalUnit` scene or one of the sub-scenes
      |  `- Header.js
      `- scenes
          |- Repositories
          |  |- components # components only used in the OrganizationalUnit/Repositories sub-scene
          |  |  `- SomeComponent.js
          |  `- index.js
          |- Members
          |  `- ...
          |- Organizations
          |  `- ...
          `- Settings
             `- ...
```

## Testability of code

Code (especially components) should be written as testable as possible.

### Proposed convention

This often means splitting the behavior of a component into a higher order component. For example:

```javascript
const Button = () => (
  <button onClick={() => window.alert("Button was clicked")}>Click me</button>
);
```
is not easily testable as one would need to mock the `window.alert` function. Instead do something like this:

```javascript
const PureButton = ({ onClick }) => <button onClick={onClick}>Click me</button>;

const withAlertOnClick = Component => (props) => (
  <Component onClick={() => window.alert("Button was clicked")} {...props} />
);

const Button = withAlertOnClick(PureButton);
```
`PureButton` can now be easily tested by passing it a mock function.

Same goes for components that are getting data via `graphql`, components using Formik, etc.

## Test file locations

We currently have two different conventions:

1. Put tests in a `__tests__` directory with the suffix `.test.js`
2. Put tests alongside the file with a `.test.js` suffix

Also possible:

1. Put tests in a `__tests__` directory without the suffix `.test.js`
2. Use the suffix `.spec.js`
3. Use a separate directory structure as we do in Ruby

### Proposed convention

I like having the test files close the the tested files because it makes finding the corresponding tests easier. However I don't have any preference on a `__tests__` directory or suffix/no-suffix, as long as we are consistent.

## Helpers (functions)

We currently have one global `helpers` directory. Importing these can be painful (only relative imports are possible).

### Proposed convention

Group helpers like the components proposal above. We have a global `helpers` directory, but each scene can have its own `helpers` directory (or whatever it should be called).

## Helpers (components)

Sometimes one needs helper components that are only relevant in one file or component. We should decide when it is appropriate to split them into their own file.

### Proposed convention

No proposal.

## Exports (named vs. default)

We're pretty inconsistent when it comes to named exports and default exports. Some people [advocate against using default exports](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html).

### Proposed convention

I would avoid using default exports for the points linked above. It also makes it unclear what the default export is if a file exports multiple things (see the `Components vs. Containers` point).

## Class components vs functional components

We're mostly using functional components at the moment, but there are also some Class components.

### Proposed convention

Use functional components. If lifecycle hooks or state are needed, these can be added to functional components using recompose. This separates the presentation (the functional component) from the behavior easily and more obviously and makes both easier to test (see `Testability of Code`).

Also: Use Arrow functions instead of `function` to avoid Javascript `this` issues and to be consistent with the rest of the code base. It's also shorter :smile: 

## ...?

If there are any other inconsistencies in the code base or structure (or questions about convention), please add a comment. Also, of course, if you have differing proposals, also add a comment.

Resources:

- https://www.sitepoint.com/organize-large-react-application/
- https://medium.com/@dominik.t/complete-guide-to-structuring-large-react-redux-apps-bc91e2136d4c
- https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1

**Comment by eugenk** [comment]
* Components vs. Containers vs. Scenes: Ok. No more "Containers". And prefix the pure components with `Pure` (`PureMyComponent`) and export the "Container" as `MyComponent`.
* Testability of code: Agree.
* Test file locations: I like "Put tests in a *__tests__* directory with the suffix `.test.js`".
* Helpers (functions/components): What about helpers that are needed in many components? Put them in a directory a level higher (like lifting state up in React)?
* Exports (named vs. default): Agree. No default exports.
* Class components vs functional components: Agree. No class components.

**Comment by phyrog** [comment]
Helpers: Exactly. What I'm currently doing for helper components is this:

```
components
`- SomeComponent.js
```

becomes

```
components
`- SomeComponent
    |- index.js # exports `SomeComponent`
    `- HelperComponent.js # is only used in `SomeComponent` and is not re-exported by index.js
```

Now, if `HelperComponent` is needed by some other component, I would move `HelperComponent` one directory up (it's like a change from a private component to a public one):

```
components
|- HelperComponent.js
|- SomeComponent.js # uses `HelperComponent`
`- SomeOtherComponent.js # uses `HelperComponent`
```

I would do the same with helper functions, except instead of moving it one directory up, I would move it up to the nearest `helper` directory:

```
components
`- SomeComponent
    |- index.js # uses `some-related-functions.js`
    `- some-related-functions.js
```

would become

```
|- components
|  |- SomeComponent.js # uses `some-related-functions.js`
|  `- SomeOtherComponent.js # uses `some-related-functions.js`
`- helpers # or `lib` or whatever
   `- some-related-functions.js
```

That kind of brings me to another convention: **Using uppercase filenames for component files (`SomeComponent.js`)**

We could also use all lowercase file names with a `.jsx` extension for components (`some-component.jsx`).

**Comment by eugenk** [comment]
I don't have a preference on filenames (CamelCase or kebap-case), but I think we should use `.jsx` for components (as they are usually written in jsx syntax) and `.js` for helper function files.

I can imagine also using CamelCase for component files and kebap-case for helper function files. However, I'm not sure whether it cleans the structure or clutters it.

**Comment by phyrog** [comment]
So, I'm having a small problem with the "pure component and impure component in one file" thing. Until now we only tested the pure components and left the `compose` out. Problem now is that we can only ignore whole files from coverage (or with the limited set of `istanbul igore ...` comments (with don't help in this case). So when we're putting both components into the same file, our coverage will decrease significantly for these files.

So I guess, we could separate them into two files and re-export both from one file, and only test the pure one:

```javascript
// pure-some-component.jsx

export const PureSomeComponent = ...
```

```javascript
// some-component.jsx

export { PureSomeComponent } from './pure-some-component';

export const SomeComponent = ...
```

Ping @eugenk

**Comment by eugenk** [comment]
Yes, we should split this. This does not mean, though, that non-pure components should not be tested in general. Sometimes the composed functions supply very important behaviour like providing and changing state: If you click on a button `toggleFoo`, then the prop `foo` should be toggled. If there is some behaviour in the non-pure component, its file must not be excluded from the coverage.
