### ISSUE TITLE
Scrolling rubber band effect makes white background visible

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-frontend#359]
When scrolling up on a mac, there is a rubber band effect that allows to scroll past the content borders and pulls the page back to the border. This makes some white background visible between the global header and the local header.

![scrolling](https://user-images.githubusercontent.com/339751/36541727-1a77f218-17df-11e8-8c89-0beb888fb5fc.gif)

**Comment by phyrog** [comment]
Just... ugh.
