### ISSUE TITLE
Redo Mirage config from from scratch

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-frontend#41]
Implementing the API when it is needed is more difficult than implementing it as soon as it's implemented in the backend. We should redo the current configuration from scratch and model the current API completely (not just the parts that we currently need in the frontend).

Possibly investigate if https://github.com/thoughtbot/ember-json-schema or https://www.npmjs.com/package/jsonapi-to-ember-mirage could be used.

**Comment by eugenk** [comment]
I like the idea of generating the models (basic things) directly from the JSON Schema in the backend and I have tried https://github.com/thoughtbot/ember-json-schema, but it does not work out of the box with our JSON Schema definitions.

It does not use the `attributes` and `relationships` keys from the schema and only relies on the `properties` key, which is not defining a single property of the object.

I think we should follow its idea to reduce work in the long run. Then, we would not need to duplicate our models in the frontend and the backend. We could fork the project and make it work with proper JSON Schema.

**Comment by eugenk** [comment]
With my fork at https://github.com/eugenk/ember-json-schema, this works. We need some conventions, though, concerning the JSON Schema files. They are be compiled in https://github.com/ontohub/ontohub-backend/issues/71.

And we still need to resolve `$ref` in the JSON Schema.

**Comment by eugenk** [comment]
Instructions to try this:
1. backend: `git checkout 71-structure_json_schema_files`
1. backend: `rails s`
1. frontend: `git checkout 41-redo_mirage_config_from_from_scratch`
1. frontend: `ln -s <ontohub-backend-repo>/spec/support/api/schemas app/schema` (in the repository-root)
1. frontend: `ember s`
1. http://localhost:4200/ada/repo0

**Comment by eugenk** [comment]
I added a commit to 41-redo_mirage_config_from_from_scratch that should resolve `$ref`s, but it doesn't work because it tries to resolve them relative to the  address (e.g. http://localhost:7357/2173/tests/other.json instead of the local path `./other`). I don't have an idea of how to do this.

**Comment by phyrog** [comment]
Closed in #62.
