### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-frontend#59]
React properly to authorisation failures of https://github.com/ontohub/ontohub-backend/issues/87.

**Comment by phyrog** [comment]
Related: #47

**Comment by eugenk** [comment]
Carefully think about the status codes we return for unauthorised access. If a private resource (e.g. repository) is accessed without permission, it should be a 404 to hide the existence of said resource.

**Comment by phyrog** [comment]
Should be handled implicitly on each component, so I'll close this.
