### ISSUE TITLE
Consider using prettier

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-frontend#83]
[prettier](https://github.com/prettier/prettier) is a tool to format JS code according to some opinionated set of rules. While some of our eslint rules differ with the output of prettier, we could [combine eslint with prettier](https://github.com/not-an-aardvark/eslint-plugin-prettier), so we could easily just run `eslint --fix` to format the code with prettier first and then fix problems with our specific style rules.

There might be problems with conflicting rules when using the above plugin, so we should investigate this first.

**Comment by eugenk** [comment]
I made prettier work with [neovim](https://neovim.io) using [neomake](https://github.com/neomake/neomake) - every time a javascript/jsx file is saved, it is reformatted and reloaded. If future generations are interested, here's the relevant part of the vimrc using [vimplug](https://github.com/junegunn/vim-plug):

```vim
call plug#begin('~/.vim/plugged')
Plug 'neomake/neomake'
call plug#end()

let g:neomake_javascript_prettier_maker = {
    \ 'exe': 'prettier-eslint',
    \ 'args': ['--write', '%:p']
    \ }
let g:neomake_javascript_enabled_makers = ['prettier', 'eslint', 'flow']
let g:neomake_jsx_enabled_makers = ['prettier', 'eslint', 'flow']
augroup neomake_augroup
  autocmd!
  autocmd BufWritePost * Neomake
  autocmd BufWritePost * call neomake#Make(1, [], function('s:Neomake_callback'))
  function! s:Neomake_callback(options)
    if (a:options.name ==? 'prettier') && (a:options.status == 0)
      edit
    endif
  endfunction
augroup END
```

**Comment by phyrog** [comment]
Btw we could even go as far as adding prettier-eslint as a pre-commit hook (I'm not sure I like a tool changing my code when I think I'm just committing code, though)

**Comment by eugenk** [comment]
I thought about a pre-commit hook, too, and I have the same concerns. I want to see the exact code I'm committing before I'm committing. I think we should stick to the in-editor solution.

**Comment by phyrog** [comment]
I just tested the `eslint-plugin-prettier` (checks files against prettier output during eslint), which checks if the code conforms with the output of prettier, but this won't work with using `prettier-eslint` (formats code with prettier first and then `eslint --fix`). We would just get errors about missing semicolons etc. So I guess we have two options:

1. Use `prettier-eslint` with our own style rules (no semicolon, single-quoted strings, ...), but have no CI check if the code is prettier formatted
1. Use `eslint-plugin-prettier`, swallowing the opinionated output of prettier, but being able to see if committed code was formatted with prettier

I actually kind of like option 2, as this would mean we won't accidentally reformat code in the same file we didn't change. I could live with double-quoted strings and semicolons (especially if they are inserted automatically on save).

**Comment by phyrog** [comment]
Using prettier-eslint on the react version, so I'll close this
